# Generated by Django 5.1.7 on 2025-03-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portpolio", "0003_alter_internship_phone_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internship",
            name="phone_no",
            field=models.IntegerField(max_length=60),
        ),
    ]
