# Generated by Django 5.1.7 on 2025-03-25 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portpolio", "0004_alter_internship_phone_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internship",
            name="phone_no",
        ),
        migrations.AddField(
            model_name="internship",
            name="phonenumber",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="internships",
                to="portpolio.contact",
            ),
        ),
    ]
