# Generated by Django 5.1.7 on 2025-03-25 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portpolio", "0006_alter_internship_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internship",
            name="phonenumber",
            field=models.ForeignKey(
                default=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portpolio.contact",
            ),
        ),
    ]
