# Generated by Django 5.1.7 on 2025-03-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portpolio", "0008_alter_internship_usn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internship",
            name="usn",
            field=models.BooleanField(default=True, max_length=60),
        ),
    ]
