# Generated by Django 5.1.7 on 2025-03-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portpolio", "0012_alter_internship_usn"),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="token_number",
            field=models.CharField(
                blank=True, editable=False, max_length=12, unique=True
            ),
        ),
    ]
