# Generated by Django 5.1.7 on 2025-03-25 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portpolio", "0013_internship_token_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internship",
            name="token_number",
        ),
    ]
