# Generated by Django 5.1.7 on 2025-03-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portpolio", "0014_remove_internship_token_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internship",
            name="phonenumber",
            field=models.CharField(default=4, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="internship",
            name="usn",
            field=models.CharField(max_length=10),
        ),
    ]
