# Generated by Django 5.1.7 on 2025-03-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portpolio", "0015_alter_internship_phonenumber_alter_internship_usn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internship",
            name="phonenumber",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
