# Generated by Django 5.1.7 on 2025-03-26 06:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portpolio", "0016_alter_internship_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internship",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
